name: bond_core

packages:
  - packages/*
  - packages/*/packages/*
  - packages/*/packages/*/example

scripts:
  analyze:
    exec: dart analyze .
    description: Analyzes the project's Dart code to identify any static errors.

  fix:
    exec: dart fix --apply
    description: Applies Dart fixes to automatically correct some of the issues found during static analysis.

  format:
    exec: dart format .
    description: Formats Dart source code to follow a recommended, canonical style.

  lint:all:
    exec: melos run analyze && melos run fix && melos run format
    description: Runs all the previous commands in sequence analysis, fixes, and formatting.

  publish:
    exec: melos flutter pub publish --dry-run
    description: Publishes all packages to pub.dev.