name: bond_socialite
description:  A Flutter package for easy integration of social logins like Google and Apple, providing a uniform interface, automation tools, and ready-to-use buttons.
version: 0.1.0
homepage: https://github.com/onestudio-co/flutter-bond

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  dependency_manipulator: ^0.0.6
  file_based_transaction_manager: ^0.0.4
  args: ^2.2.2