name: bond_core
description: Bond Core Foundational Library for the Flutter Bond framework.
version: 0.0.1+4
repository: https://github.com/onestudio-co/bond-core/tree/main/packages/core
homepage: https://github.com/onestudio-co/flutter-bond

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.4

